### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by HelgaListopad** [R-u-Slick/WebixTest#1]
The implementation is almost correct, but requires a few changes:

1. The static height of the app does not allow viewing it in a smaller browser window (moreover, the footer can easily collapse to 0 if there is no space for it).
https://github.com/R-u-Slick/WebixTest/blob/e22eea5e54aa2086b8d76b654a7381ff7ee87236/layout.html#L31
If the layout shrinks without this setting, pay attention to the nested views, as one of them could limit the parent layout with a static size (in our case, it's the form).
By default, all form inputs have a constant height. To resolve the issue here, it would be great to add a [spacer](https://slides.com/ihelga/webixlayouts#/18) next to existing elements.
Note that the footer of your app should be quite thin.

2. Data binding is a really great way to link a form to a table, yet it needs an improvement.
This feature relies on the current selection. In order to add a new record and not spoil the existing (selected) data, [reset the selection](https://docs.webix.com/api__selectionmodel_unselectall.html) in the table in addition to the `clear` command:
https://github.com/R-u-Slick/WebixTest/blob/e22eea5e54aa2086b8d76b654a7381ff7ee87236/layout.html#L72

**Comment by R-u-Slick** [comment]
Helga, thanks a lot for your review. I fixed both problems:
1. To solve the problem with the app height I added a spacer to the form and also removed the autoheight property from the datatable. 
2. In order to protect the existing data in the table I added an unselect all function to the clear button.

**Comment by HelgaListopad** [comment]
Yep, the mentioned issues are fixed.

However, please [omit](https://docs.webix.com/desktop__styling.html#wherecsscanandcannotbeapplied) anything that can change the size of a component in CSS:
https://github.com/R-u-Slick/WebixTest/blob/6323bce91f7e7e455e6b4059e174804ea433a85f/style.css#L22

If the view has a border and you need to hide it with CSS, `border-color: transparent` is always the safest option.
Sizing (incl. border existence/styling) in Webix is implemented in JS logic, and it won't have any information about extra CSS-based changes. As a result, this particular line can shift the view in 1px.

**Comment by R-u-Slick** [comment]
Thanks a lot for your feedback. 
 I fixed this issue.

**Comment by HelgaListopad** [comment]
Great, thank you!
